### ISSUE TITLE
License

### ISSUE THREAD

**Issue by kungfooman** [fonsp/resim#34]
This looks super interesting and I wonder about the license. Could you please assign one?

**Comment by fonsp** [comment]
Thanks for pointing that out! Since you're the only person on the planet who is interested - would the MIT license work for you? ☺️

**Comment by kungfooman** [comment]
MIT license would be perfect, one of the best licenses ever 🙏

**Comment by fonsp** [comment]
Here you go!

**Comment by fonsp** [comment]
Let me know if you use this for something cool! (or if you have trouble using it)

**Comment by kungfooman** [comment]
Thank you, I will let you know, once I have something interesting! I like WebGL and browser games a lot, so I will probably try to port the code at some point to PlayCanvas, so it would have PBR rendering and lots of light types and shader effects etc.

**Comment by fonsp** [comment]
Cool! The core ideas of this project are all in the vertex shader (which deforms geometry relativistically) and the fragment shader (for doppler and rel. brightness). The rest was mostly me getting excited about writing a 3D engine without comments 🌈
